<a href="https://colab.research.google.com/github/shafiqshams/practical-deep-learning-using-pytorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print('GPU is available')
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print('GPU is not available, using CPU.')

GPU is not available, using CPU.


## Creating a Tensor

In [3]:
# add empty tensor with specific shape
# creating empty space in memory
a = torch.empty(2,3)
type(a)

torch.Tensor

In [4]:
# using zeros
# mainly for initializing biases with 0
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
# with random value initialization
torch.rand(2,3)

tensor([[0.2651, 0.1342, 0.7328],
        [0.9514, 0.9987, 0.6869]])

In [10]:
# manual_seed
# to get the same values and acheive reproducibility
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
# using arange
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [15]:
# using linspace
# linearly spaced: 0 - 10, 10 or 5 evenly spaced values
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [16]:
# using eye
# Identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
# using full
torch.full((2,3), 5)

tensor([[5, 5, 5],
        [5, 5, 5]])

## Tensor Shapes

In [26]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
x.shape

torch.Size([2, 3])

In [28]:
# copy shape of a tensor
torch.empty_like(x)

tensor([[3616445622929465956, 6068092717591768373, 3473465217021260594],
        [6499037521336349742, 7309453675965983778, 8315168162784306286]])

In [30]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [31]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [37]:
# error: because the data type is not provided.
# rand creates values between 0 - 1 and our x is int64 datatype
# therefore error of mismatch datatype
# x.dtype

# torch.rand_like(x)
