<a href="https://colab.research.google.com/github/shafiqshams/practical-deep-learning-using-pytorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print('GPU is available')
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print('GPU is not available, using CPU.')

GPU is not available, using CPU.


## Creating a Tensor

In [ ]:
# add empty tensor with specific shape
# creating empty space in memory
a = torch.empty(2,3)
type(a)

torch.Tensor

In [ ]:
# using zeros
# mainly for initializing biases with 0
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
# with random value initialization
torch.rand(2,3)

tensor([[0.2651, 0.1342, 0.7328],
        [0.9514, 0.9987, 0.6869]])

In [ ]:
# manual_seed
# to get the same values and acheive reproducibility
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# using arange
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [ ]:
# using linspace
# linearly spaced: 0 - 10, 10 or 5 evenly spaced values
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [ ]:
# using eye
# Identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
# using full
torch.full((2,3), 5)

tensor([[5, 5, 5],
        [5, 5, 5]])

## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
# copy shape of a tensor
torch.empty_like(x)

tensor([[3616445622929465956, 6068092717591768373, 3473465217021260594],
        [6499037521336349742, 7309453675965983778, 8315168162784306286]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# error: because the data type is not provided.
# rand creates values between 0 - 1 and our x is int64 datatype
# therefore error of mismatch datatype
# fixed it using dtype param
torch.rand_like(x, dtype=torch.float32)


tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

## Tensor Data types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type when creating a tensor
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# changing existing tensor data type
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operations

In [5]:
x = torch.rand(2,2)
x

tensor([[0.7391, 0.7968],
        [0.5519, 0.7815]])

In [6]:
# addition
x + 2

tensor([[2.7391, 2.7968],
        [2.5519, 2.7815]])

In [7]:
# subtraction
x - 2

tensor([[-1.2609, -1.2032],
        [-1.4481, -1.2185]])

In [8]:
# multiplication
x * 3

tensor([[2.2174, 2.3903],
        [1.6557, 2.3445]])

In [11]:
# division
x / 3

tensor([[0.2464, 0.2656],
        [0.1840, 0.2605]])

In [14]:
# integer division
(x * 100) // 3

tensor([[24., 26.],
        [18., 26.]])

In [20]:
# mod: remainder
(x * 100) % 3

tensor([[1.9129, 1.6776],
        [1.1911, 0.1504]])

In [21]:
# power
x ** 2

tensor([[0.5463, 0.6349],
        [0.3046, 0.6107]])

### 2. Element wise operation

In [22]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2380, 0.3129, 0.2067],
        [0.2775, 0.6398, 0.2120]])
tensor([[0.9378, 0.8752, 0.1334],
        [0.6275, 0.9894, 0.4620]])


In [25]:
# add
a + b

tensor([[1.1758, 1.1881, 0.3401],
        [0.9050, 1.6292, 0.6740]])

In [26]:
# sub
a - b

tensor([[-0.6997, -0.5623,  0.0733],
        [-0.3500, -0.3496, -0.2499]])

In [27]:
# multiply
a * b

tensor([[0.2232, 0.2739, 0.0276],
        [0.1741, 0.6330, 0.0980]])

In [28]:
# division
a / b

tensor([[0.2538, 0.3575, 1.5496],
        [0.4423, 0.6467, 0.4590]])

In [29]:
# power
a ** b

tensor([[0.2603, 0.3617, 0.8104],
        [0.4474, 0.6428, 0.4885]])

In [30]:
# mod
a % b

tensor([[0.2380, 0.3129, 0.0733],
        [0.2775, 0.6398, 0.2120]])

In [31]:
c = torch.tensor([1, -2, 3, -4])

In [32]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [33]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [34]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [35]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [36]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [37]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [39]:
# clamp
# values in certain range (2-3)
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [54]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 9., 8.],
        [2., 2., 6.]])

In [57]:
# sum
torch.sum(e)

tensor(34.)

In [58]:
# sum along columns
torch.sum(e, dim=0)

tensor([ 9., 11., 14.])

In [59]:
# sum along rows
torch.sum(e, dim=1)

tensor([24., 10.])

In [60]:
# mean
torch.mean(e)

tensor(5.6667)

In [61]:
# mean along col
torch.mean(e, dim=0)

tensor([4.5000, 5.5000, 7.0000])

In [63]:
# mean along row
torch.mean(e, dim=1)

tensor([8.0000, 3.3333])

In [64]:
# median
torch.median(e)

tensor(6.)

In [65]:
# max
torch.max(e)

tensor(2.)

In [67]:
# min
torch.min(e)

tensor(2.)

In [69]:
# product
torch.prod(e)

tensor(12096.)

In [70]:
# standard deviation
torch.std(e)

tensor(3.0111)

In [71]:
# variance
torch.var(e)

tensor(9.0667)

In [72]:
# argmax
torch.argmax(e)

tensor(1)

In [73]:
# argmin
torch.argmin(e)

tensor(3)

### 4. Matrix operations

In [11]:
f = torch.randint(size=(2,3), low=0, high=5)
g = torch.randint(size=(3,2), low=0, high=5)

print(f)
print(g)

tensor([[4, 0, 3],
        [1, 4, 0]])
tensor([[4, 3],
        [4, 1],
        [1, 1]])


In [12]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[19, 15],
        [20,  7]])

In [13]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [14]:
# dot product
torch.dot(vector1, vector2)

tensor(11)

In [18]:
# transpose
torch.transpose(f, 0, 1)

tensor([[4, 1],
        [0, 4],
        [3, 0]])

In [19]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 0., 1.],
        [9., 0., 1.],
        [4., 4., 2.]])

In [21]:
# determinant
torch.det(h)

tensor(36.)

In [22]:
# inverse
torch.inverse(h)

tensor([[-0.1111,  0.1111,  0.0000],
        [-0.3889, -0.1111,  0.2500],
        [ 1.0000,  0.0000,  0.0000]])

### 5. Comparison operations

In [23]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[1, 5, 6],
        [3, 2, 4]])
tensor([[0, 7, 5],
        [0, 5, 6]])


In [24]:
# greater than
i > j

tensor([[ True, False,  True],
        [ True, False, False]])

In [25]:
# less than
i < j

tensor([[False,  True, False],
        [False,  True,  True]])

In [26]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [28]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [29]:
# greater than equal to
i >= j

tensor([[ True, False,  True],
        [ True, False, False]])

In [30]:
# less than equal to
i <= j

tensor([[False,  True, False],
        [False,  True,  True]])

## Inplace Operations

In [31]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2029, 0.0607, 0.9190],
        [0.2250, 0.6325, 0.1608]])
tensor([[0.3704, 0.8230, 0.7857],
        [0.4297, 0.6908, 0.3671]])


In [32]:
# store result in m
# inplace changes
m.add_(n)

tensor([[0.5734, 0.8837, 1.7047],
        [0.6547, 1.3233, 0.5280]])

In [37]:
# original tensor m is updated
m

tensor([[0.5734, 0.8837, 1.7047],
        [0.6547, 1.3233, 0.5280]])

In [38]:
# value stored in a new tensor and in memory
# problematic for large dataset
torch.relu(m)

tensor([[0.5734, 0.8837, 1.7047],
        [0.6547, 1.3233, 0.5280]])

In [39]:
m.relu_()

tensor([[0.5734, 0.8837, 1.7047],
        [0.6547, 1.3233, 0.5280]])

In [40]:
m

tensor([[0.5734, 0.8837, 1.7047],
        [0.6547, 1.3233, 0.5280]])

## Copying a Tensor

In [42]:
a = torch.rand(2,3)
a

tensor([[0.9952, 0.6116, 0.1145],
        [0.4705, 0.2970, 0.0198]])

In [44]:
b = a
b

tensor([[0.9952, 0.6116, 0.1145],
        [0.4705, 0.2970, 0.0198]])

In [45]:
a[0,0] = 0

In [46]:
b

tensor([[0.0000, 0.6116, 0.1145],
        [0.4705, 0.2970, 0.0198]])

In [47]:
id(a)

133953570367808

In [48]:
id(b)

133953570367808

In [49]:
b = a.clone()

In [50]:
a[0][0] = 10

In [51]:
a

tensor([[10.0000,  0.6116,  0.1145],
        [ 0.4705,  0.2970,  0.0198]])

In [52]:
b

tensor([[0.0000, 0.6116, 0.1145],
        [0.4705, 0.2970, 0.0198]])

In [53]:
id(a)

133953570367808

In [54]:
id(b)

133953252303296